pr:
  branches:
    include:
      - master
  paths:
    exclude:
    - ".devcontainer"
    - ".hooks"
    - ".vscode"
    - ".github"
    - docs

trigger:
  paths:
    exclude:
    - docs
    - "zapai/*"
    - "azure-ipam/*"
    - "dropgz/*"
  tags:
    include:
    - "*"

stages:
  - stage: setup
    displayName: ACN
    jobs:
      - job: env
        displayName: Setup
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        steps:
          - script: |
              BUILD_NUMBER=$(Build.BuildNumber)
              echo "##vso[task.setvariable variable=StorageID;isOutput=true]$(echo ${BUILD_NUMBER//./-})"
              echo "##vso[task.setvariable variable=Tag;isOutput=true]$(make version)"
              echo "##vso[task.setvariable variable=cniVersion;isOutput=true]$(make cni-version)"
              echo "##vso[task.setvariable variable=npmVersion;isOutput=true]$(make npm-version)"
              cat /etc/os-release
              uname -a
              sudo chown -R $(whoami):$(whoami) .
              go version
              go env
              which go
              echo $PATH
            name: "EnvironmentalVariables"
            displayName: "Set environmental variables"
            condition: always()

  - stage: containerize
    displayName: Build Images
    dependsOn:
      - setup
    jobs:
      - job: containerize_windows_amd64
        timeoutInMinutes: 120
        displayName: Build Images
        variables:
          TAG: $[ stagedependencies.setup.env.outputs['EnvironmentalVariables.Tag'] ]
        pool:
          name: "$(BUILD_POOL_NAME_LINUX_AMD64)"
        strategy:
          matrix:
            cns_windows_amd64:
              arch: amd64
              name: cns
              ai_path: github.com/Azure/azure-container-networking/cns/logger.aiMetadata
              ai_path_var: CNS_AI_PATH
              ai_id: ce672799-8f08-4235-8c12-08563dc2acef
              ai_id_var: CNS_AI_ID
            npm_windows_amd64:
              arch: amd64
              name: npm
              ai_path: github.com/Azure/azure-container-networking/npm.aiMetadata
              ai_path_var: NPM_AI_PATH
              ai_id: 014c22bd-4107-459e-8475-67909e96edcb
              ai_id_var: NPM_AI_ID
        steps:
          - template: containers/container-template-windows.yaml
            parameters:
              name: $(name)
              arch: $(arch)
              ai_path: $(ai_path)
              ai_path_var: $(ai_path_var)
              ai_id: $(ai_id)
              ai_id_var: $(ai_id_var)
              tag: $(TAG)

  - template: singletenancy/aks-engine/e2e-job-template.yaml
    parameters:
      name: "windows_19_03_e2e"
      displayName: "Windows 1903"
      pipelineBuildImage: "$(BUILD_IMAGE)"
      clusterDefinition: "cniWindows1903.json"
      clusterDefinitionCniTypeKey: "azureCNIURLWindows"
      clusterDefinitionCniBuildOS: "windows"
      clusterDefinitionCniBuildExt: ".zip"

  - stage: cleanup
    displayName: Cleanup
    dependsOn:
      - "windows_19_03_e2e"
    jobs:
      - job: delete_remote_artifacts
        displayName: Delete remote artifacts
        pool:
          name: $(BUILD_POOL_NAME_DEFAULT)
          demands: agent.os -equals Linux
        steps:
          - checkout: none
          - task: AzureCLI@1
            inputs:
              azureSubscription: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
              scriptLocation: "inlineScript"
              inlineScript: |
                BUILD_NUMBER=$(Build.BuildNumber)
                BUILD_NUMBER=${BUILD_NUMBER//./-}
                echo Deleting storage container with name acn-$BUILD_NUMBER and account name $(STORAGE_ACCOUNT_NAME)
                az storage container delete -n acn-$BUILD_NUMBER --account-name $(STORAGE_ACCOUNT_NAME)
            displayName: Cleanup remote Azure storage container
