apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: azure-cni-windows
  labels:
    tier: node
    app: azure-cni
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: azure-cni
  template:
    metadata:
      labels:
        tier: node
        app: azure-cni
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - windows
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\system"
      hostNetwork: true
      serviceAccountName: azure-cni
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      initContainers:
        - name: cni-drop # Will run once per node
          image: acndev.azurecr.io/cni-test-windows:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: cni-bin
              mountPath: /k/azurecni/bin/
            - name: cni-conflist
              mountPath: /k/azurecni/netconf/
      containers:
        - name: pause # Does nothing, hack to use a daemonset
          image: mcr.microsoft.com/oss/kubernetes/pause:3.6
          command: ["%CONTAINER_SANDBOX_MOUNT_POINT%/pause.exe"]
      volumes:
        - name: cni-conflist
          hostPath:
            path: /k/azurecni/netconf/
            type: DirectoryOrCreate
        - name: cni-bin
          hostPath:
            path: /k/azurecni/bin
            type: DirectoryOrCreate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-cni
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists